name: "nsupdate (rfc2136) ddclient  DDNS Updater"
description: "nsupdate DDNS Updater"
version: "1.0.0"
slug: "ddns_nsupdate_updater"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services

options:
  config: []

schema:
  config:
    - hostnames: str
      hmac_key: str
      server: str
      zone: str
