name: "ddclient DDNS Updater"
description: "ddclient DDNS Updater"
version: "1.0.0"
slug: "ddns_ddclient_updater"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services

options:
  config: []

schema:
  config:
    - hostnames: str
      protocol: str
      config: str
