name: "nsupdate DDNS Updater"
description: "nsupdate (rfc2136) DDNS Updater"
version: "1.0.1"
slug: "ddns_nsupdate"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services

options:
  config: []

schema:
  config:
    - hostnames: str
      key_name: str
      hmac_key: str
      hmac_private: str
      server: str
      zone: str
